# HallowBranch Development Environment Configuration
# https://mise.jdx.dev/

# Minimum Mise version required
min_version = "2024.9.5"

[tools]
# Node.js version for the project
nodejs = "22"
yarn = "4.10.2"

[vars]
# Project configuration
PROJECT_NAME = "HallowBranch"

# Directory paths
NEXTJS_DIR = "nextjs"

[env]
# Add node_modules/.bin to PATH for npm packages
_.path = ["{{config_root}}/nextjs/node_modules/.bin"]

# Performance and development settings
NODE_OPTIONS = "--max_old_space_size=4096"
NEXT_TELEMETRY_DISABLED = "1"

[tasks.dev]
description = "Start the development server"
depends = ["install-deps"]
dir = "nextjs"
run = "yarn dev"

[tasks.build]
description = "Build the application for production"
depends = ["install-deps"]
dir = "nextjs"
run = "yarn build"

[tasks.lint]
description = "Run code linting (check only)"
dir = "nextjs"
run = "yarn lint"

[tasks.lint-fix]
description = "Run code linting and fix issues"
dir = "nextjs"
run = "yarn lint --fix"

[tasks.format]
description = "Format code with Prettier"
dir = "nextjs"
run = "yarn prettier --write ."

[tasks.format-check]
description = "Check code formatting with Prettier"
dir = "nextjs"
run = "yarn prettier --check ."

[tasks.type-check]
description = "Run TypeScript type checking"
dir = "nextjs"
run = "yarn type-check"

[tasks.start]
description = "Start the production server"
depends = ["build"]
dir = "nextjs"
run = "yarn start"

[tasks.install-deps]
description = "Install dependencies"
dir = "nextjs"
run = "yarn install"

[tasks.supabase-start]
description = "Start local Supabase services"
run = "supabase start"

[tasks.supabase-stop]
description = "Stop local Supabase services"
run = "supabase stop"

[tasks.supabase-reset]
description = "Reset local database and apply migrations"
run = "supabase db reset"

[tasks.supabase-status]
description = "Show Supabase project status"
run = "supabase status"

[tasks.types]
description = "Generate TypeScript types from Supabase schema"
run = "supabase gen types typescript --local > nextjs/src/lib/supabase/types.ts"

[tasks.release]
description = "Run full release workflow (version, changelog, tag)"
run = "./scripts/release.sh"

[tasks.release-version]
description = "Check what the next version would be"
dir = "nextjs"
run = "npx git-conventional-commits version"

[tasks.release-changelog]
description = "Generate changelog for current version"
dir = "nextjs"
run = "npx git-conventional-commits changelog --file ../CHANGELOG.md"

[tasks.clean]
description = "Clean build artifacts and dependencies"
dir = "nextjs"
run = "rm -rf .next node_modules/.cache && yarn install"

# Project-specific aliases for convenience
[alias]
dev = "task dev"
build = "task build"
start = "task start"
lint = "task lint"
lint-fix = "task lint-fix"
format = "task format"
format-check = "task format-check"
supabase = "task supabase-start"
supabase-stop = "task supabase-stop"
types = "task types"
clean = "task clean"
release = "task release"
version = "task release-version"
changelog = "task release-changelog"

# Environment-specific variables should go in .mise.local.toml:
# [env]
# DEBUG = "true"          # Development only
# SUPABASE_LOCAL = "true" # Development only
# NODE_ENV = "development" # Development only
#
# [env.production]
# NODE_ENV = "production" # Production only
# SUPABASE_LOCAL = "false" # Production only
